server:
  port: 8001

mybatis:
  type-aliases-package: com.zhj.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false    #页面不加载缓存，修改即时生效
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://aliyun:3306/vdb1?useUnicode=true&characterEncoding=utf-8
    username: root
    password: rootzhj
eureka:
  client:
    service-url:  # 修改默认端口
      defaultZone: http://www.eureka1.com:7001/eureka/,http://www.eureka2.com:7002/eureka/,http://www.eureka3.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-hystrix-8001 # 修改eureka 默认描述信息
# info 配置
info:
 app.name: zhj-springcloud
 company.name: www.zhjweb.tech