server:
  port: 3344
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/zhuhuijie/springcloud.git
eureka:
  client:
    service-url:  # 修改默认端口
      defaultZone: http://www.eureka1.com:7001/eureka/,http://www.eureka2.com:7002/eureka/,http://www.eureka3.com:7003/eureka/
  instance:
    instance-id: springcloud-config-server-3344 # 修改eureka 默认描述信息
    prefer-ip-address: true  # ip 信息
# info 配置
info:
  app.name: zhj-springcloud
  company.name: www.zhjweb.tech